Completed first version of ExtractMinisat; MG, please note.
Handling of directories yet missing (and just tested it one some
examples).

diff --git a/Experimentation/ExperimentSystem/SolverMonitoring/ExtractMinisat b/Experimentation/ExperimentSystem/SolverMonitoring/ExtractMinisat
--- a/Experimentation/ExperimentSystem/SolverMonitoring/ExtractMinisat
+++ b/Experimentation/ExperimentSystem/SolverMonitoring/ExtractMinisat
@@ -7,23 +7,55 @@
 # License, or any later version.
 
 # Reads minisat output from standard input, printing the extracted numerical
-# data to standard output.
+# data together with a header (R table-style) to standard output.
+
+# One optional argument is allowed:
+# - if it is "header-only" then only the header is printed
+# - otherwise (with one argument) only the data is printed.
+# (If there is no argument, then both header and data are printed.)
 
 set -o errexit
 set -o nounset
 
 script_name="ExtractMinisat"
-version_number=0.0.5
+version_number=0.0.8
 
-# Extraction of path to source code:
+if ([ $# -ge 2 ]) then
+  echo -e "ERROR[${script_name}]: At most one parameter is allowed,\n" \
+    " either string \"header-only\" or string \"data-only\"."
+  exit 1
+fi
+
+if ([ $# -eq 1 ]) then
+  if ([ $1 == header-only ]) then
+    mode=header-file
+  else
+    mode=data-file
+  fi
+else
+  mode=both-file
+fi
+
+# Computation of path to source code:
 src_path="${BASH_SOURCE[0]}";
-while([ -h "${src_path}" ]) do src_path=$(readlink "${src_path}"); done
+while ([ -h "${src_path}" ]) do src_path=$(readlink "${src_path}"); done
 cd $(dirname ${src_path}) > /dev/null
 src_path=$(pwd)
 cd - > /dev/null
 
-extract_awk=${src_path}/ExtractMinisat.awk
+if ([ ${mode} == header-file ]) then
+  header="$(cat ${src_path}/headers/minisat)"
+  echo "${header}"
+  exit 0
+elif ([ ${mode} == data-file ]) then
+  extract_awk=${src_path}/ExtractMinisat.awk
+  awk -f ${extract_awk}
+  exit 0
+fi
 
+header="$(cat ${src_path}/headers/minisat)"
+echo "${header}"
+extract_awk=${src_path}/ExtractMinisat.awk
 awk -f ${extract_awk}
 
 exit 0
