Application tests expanded.

diff --git a/Satisfiability/Transformers/Generators/Queens/GenericSAT/RunTests b/Satisfiability/Transformers/Generators/Queens/GenericSAT/RunTests
--- a/Satisfiability/Transformers/Generators/Queens/GenericSAT/RunTests
+++ b/Satisfiability/Transformers/Generators/Queens/GenericSAT/RunTests
@@ -48,3 +48,137 @@ for S in "${programs[@]}"; do
   done
 
 done
+
+program1="./ExpQueens"
+program2="valgrind -q ./ExpQueens_debug"
+declare -a programs=("${program1}" "${program2}")
+
+declare -a outcomes0=(0 1 0 0 2 10 4 40 92)
+declare -a outcomes1=(0 1 3 5 7 19 51 155 453)
+declare -a outcomes2=(0 0 1 2 3 5 8 11 17)
+declare -a outcomes3=(0 0 3 5 1 0 5 3 9)
+declare -a outcomes4=(0 1 0 0 3 19 1 3 3)
+declare -a outcomes5=(0 0 1 1 1 2 3 4 4)
+declare -a outcomes6=(0 1 inf inf 2 1 6.5 1.95 2.46739)
+
+for S in "${programs[@]}"; do
+  echo $S
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N})"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N}\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
+
+for S in "${programs[@]}"; do
+  echo $S "p"
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N} p)"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N} p\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
+
+declare -a outcomes0=(0 1 0 0 2 10 4 40 92)
+declare -a outcomes1=(0 1 3 9 23 87 343 1543 7911)
+declare -a outcomes2=(0 0 1 4 9 14 25 34 49)
+declare -a outcomes3=(0 0 3 9 7 43 43 211 875)
+declare -a outcomes4=(0 1 0 0 1 3 1 3 3)
+declare -a outcomes5=(0 0 1 1 2 2 3 4 5)
+declare -a outcomes6=(0 1 inf inf 6 4.4 43 19.3 43)
+
+for S in "${programs[@]}"; do
+  echo $S "a"
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N} a)"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N} a\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
+
+declare -a outcomes0=(0 1 0 0 2 10 4 40 92)
+declare -a outcomes1=(0 1 3 5 11 27 75 209 783)
+declare -a outcomes2=(0 0 1 2 4 6 9 12 17)
+declare -a outcomes3=(0 0 3 5 3 1 13 5 31)
+declare -a outcomes4=(0 1 0 0 1 3 1 3 9)
+declare -a outcomes5=(0 0 1 1 2 2 3 4 5)
+declare -a outcomes6=(0 1 inf inf 3 1.4 9.5 2.625 4.26087)
+
+for S in "${programs[@]}"; do
+  echo $S "f"
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N} f)"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N} f\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
+
+declare -a outcomes0=(0 1 0 0 2 10 4 40 92)
+declare -a outcomes1=(0 1 3 7 17 43 129 361 1455)
+declare -a outcomes2=(0 0 1 3 6 13 18 25 37)
+declare -a outcomes3=(0 0 3 7 3 3 19 17 77)
+declare -a outcomes4=(0 1 0 0 1 3 1 3 3)
+declare -a outcomes5=(0 0 1 1 2 2 3 4 4)
+declare -a outcomes6=(0 1 inf inf 4.5 2.2 16.25 4.525 7.91304)
+
+for S in "${programs[@]}"; do
+  echo $S "r"
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N} r)"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N} r\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
+
+declare -a outcomes0=(0 1 0 0 2 10 4 40 92)
+declare -a outcomes1=(0 1 3 5 13 37 119 435 1801)
+declare -a outcomes2=(0 0 1 2 5 10 17 26 37)
+declare -a outcomes3=(0 0 3 5 3 9 35 59 235)
+declare -a outcomes4=(0 1 0 0 1 3 1 1 3)
+declare -a outcomes5=(0 0 1 1 2 2 3 4 4)
+declare -a outcomes6=(0 1 inf inf 3.5 1.9 15 5.45 9.79348)
+
+for S in "${programs[@]}"; do
+  echo $S "s"
+  for (( N=1; N<=maxN; ++N )); do
+    solvercall="${S/ $N}"
+    echo "Testcase: ${solvercall}" > /dev/null
+    result="$(${solvercall} ${N} s)"
+    expected=$'c solutions                             '${outcomes0[$N]}$'\nc nodes                                 '${outcomes1[$N]}$'\nc height                                '${outcomes2[$N]}$'\nc max_unodes                            '${outcomes3[$N]}$'\nc max_snodes                            '${outcomes4[$N]}$'\nc HortonStrahler                        '${outcomes5[$N]}$'\nc q=leaves/sols                         '${outcomes6[$N]}
+    if [[ "$result" != "$expected" ]]; then
+      echo -e "${error}\"${S} ${N} s\" yields \"${result}\", but should yield ${expected}."
+      exit $N
+    fi
+  done
+
+done
