Added sub-target maxima_test to new_check.
Yet only at ComputerAlgebra-level a generic makefile is placed,
so only at that level yet tests are executed (by new_check
resp. maxima_test).

Also backtrace-application from Maxima-assert removed, since
it had no effect.

Run "oklib --prebuild" to update.

diff --git a/Buildsystem/OKlibBuilding/Makefile b/Buildsystem/OKlibBuilding/Makefile
--- a/Buildsystem/OKlibBuilding/Makefile
+++ b/Buildsystem/OKlibBuilding/Makefile
@@ -1,5 +1,5 @@
 # Oliver Kullmann, 6.3.2002 (Swansea)
-# Copyright 2002-2007 Oliver Kullmann
+# Copyright 2002-2007, 2008 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
@@ -739,7 +739,7 @@ check : test testop
 # Perform all tests (unoptimised and optimised) from the new 
 # test system.
 # ----------------------------------------------------------
-new_check : new_test new_testop
+new_check : new_test new_testop maxima_test
 # ----------------------------------------------------------
 
 # ----------------------------------------------------------
@@ -800,6 +800,24 @@ $(testop_timestamp) : $(new_test_program_optimised) | $(test_aux_dir)
 	$(Test_tool) $(new_test_program_optimised) $(test_parameters)
 	touch $(testop_timestamp)
 # ----------------------------------------------------------
+
+# The testsystem for the Maxima system
+
+maxima_testobject_files_okl := $(shell find $(srcdir)/* -path "/*/testobjects/*.mac")
+
+.PHONY : $(maxima_testobject_files_okl)
+
+maxima_test : $(maxima_testobject_files_okl)
+
+$(maxima_testobject_files_okl) : $(OKsystem)/%.mac :
+	$(preprocessing_call) $(OKbuildsystem)/MasterScript/SpecialProcessing/maxima-init.mac > $(maxima_share_dir_okl)/maxima-init.mac
+	export OKL_MAXIMA_TEST_FILENAME=$*;\
+	export OKL_MAXIMA_TEST_OUTPUT=$(maxima_test_aux_dir_okl)/$*;\
+	mkdir -p $$(dirname $${OKL_MAXIMA_TEST_OUTPUT}); $(postcondition)\
+	rm -f $${OKL_MAXIMA_TEST_OUTPUT}; $(postcondition)\
+	$(preprocessing_call) $(OKbuildsystem)/OKlibBuilding/Targets/new_check/maxima_init_tests.mac >> $(maxima_share_dir_okl)/maxima-init.mac; $(postcondition)\
+	$(maxima_call_okl) --batch-string=""; $(postcondition)\
+	if [[ -f $${OKL_MAXIMA_TEST_OUTPUT} ]]; then echo "ERROR: $${OKL_MAXIMA_TEST_OUTPUT}"; exit 1; fi
 
 # ----------------------------------------------------------
 # force
