Transferred four more tests.

diff --git a/Satisfiability/Quantification/DQCNF/app_tests/Makefile b/Satisfiability/Quantification/DQCNF/app_tests/Makefile
--- a/Satisfiability/Quantification/DQCNF/app_tests/Makefile
+++ b/Satisfiability/Quantification/DQCNF/app_tests/Makefile
@@ -4,7 +4,7 @@
 # the Free Software Foundation and included in this library; either version 3 of the
 # License, or any later version.
 
-# Version 0.1.1
+# Version 0.1.2
 
 SHELL := /bin/bash
 .SUFFIXES :
@@ -18,7 +18,7 @@ translator2 :="AutarkiesL1"
 
 transcall =$(subst T2,$(translator2), $(subst T1,$(translator1),$(1)))
 
-targetlist_0 := E0 E1 E2 E3 E4 E5 E6 E7 E8 E9 E10
+targetlist_0 := E0 E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14
 ct = $(addsuffix _T1, $(1)) $(addsuffix _T2, $(1))
 targetlist := $(call ct,$(targetlist_0))
 
@@ -114,3 +114,36 @@ $(call ct,E10) : E10_% :
 	if  (( returncode != 3 )); then
 	echo "ERROR with translator \"$$S\" on bad p-line (trailing): wrong return-code $${returncode}."; exit 1
 	fi
+
+$(call ct,E11) : E11_% :
+	@S="$(call transcall,$*)"
+	echo -e "p cnf 0 0\nc" | $$S "-cin" -nil -nil n 2> /dev/null
+	returncode=$$?
+	if  (( returncode != 28 )); then
+	echo "ERROR with translator \"$$S\" on illegal comment: wrong return-code $${returncode}."; exit 1
+	fi
+
+$(call ct,E12) : E12_% :
+	@S="$(call transcall,$*)"
+	echo -e "p cnf 0 0\nc" | $$S "-cin" -nil -nil g
+	returncode=$$?
+	if  (( returncode != 0 )); then
+	echo "ERROR with translator \"$$S\" on legal comment: wrong return-code $${returncode}."; exit 1
+	fi
+
+$(call ct,E13) : E13_% :
+	@S="$(call transcall,$*)"
+	echo -e "p cnf 1 0\na 1 0\na 0" | $$S "-cin" -nil -nil n 2> /dev/null
+	returncode=$$?
+	if  (( returncode != 11 )); then
+	echo "ERROR with translator \"$$S\" on repeated a-line: wrong return-code $${returncode}."; exit 1
+	fi
+
+$(call ct,E14) : E14_% :
+	@S="$(call transcall,$*)"
+	echo -e "p cnf 1 0\na 1 0\na 0" | $$S "-cin" -nil -nil g
+	returncode=$$?
+	if  (( returncode != 0 )); then
+	echo "ERROR with translator \"$$S\" on legal repeated (empty) a-line: wrong return-code $${returncode}."; exit 1
+	fi
+
