Corrected error with checking total clause-number.
Now also the number of repeated clauses in the input is output.
More tests needed.

diff --git a/Satisfiability/Quantification/DQCNF/app_tests/RunTests b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
--- a/Satisfiability/Quantification/DQCNF/app_tests/RunTests
+++ b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
@@ -476,6 +476,24 @@ set -e
     exit 1
   fi
 
+set +e
+  echo -e "p cnf 1 0\n1 -1 0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 8 )); then
+    echo "ERROR with translator \"${S}\" on too many clauses (tautologicals): wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 1 1\n1 -1 0" | $S "-cin" -nil -nil vs 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 0 )); then
+    echo "ERROR with translator \"${S}\" on legal example (tautological clause): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+
 
   file="${testdir}/Maxima_2903.dqdimacs"
 set +e
