Improving and checking input-errors related to reading clauses.

diff --git a/Satisfiability/Quantification/DQCNF/app_tests/RunTests b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
--- a/Satisfiability/Quantification/DQCNF/app_tests/RunTests
+++ b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
@@ -391,6 +391,91 @@ set -e
     exit 1
   fi
 
+set +e
+  echo -e "p cnf 1 0\nd 1 0\nx" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 6 )); then
+    echo "ERROR with translator \"${S}\" on bad first read in clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo -e "p cnf 1 0\nd 1 0\n2" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 7 )); then
+    echo "ERROR with translator \"${S}\" on variable too big in clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 1 0\nd 1 0\n-2" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 7 )); then
+    echo "ERROR with translator \"${S}\" on variable too big in clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo -e "p cnf 1 0\na 1 0\n1 -1 x0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 6 )); then
+    echo "ERROR with translator \"${S}\" on bad read in a-tautological clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 1 0\ne 1 0\n1 -1 x0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 6 )); then
+    echo "ERROR with translator \"${S}\" on bad read in e-tautological clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 1 0\nd 1 0\n1 -1 x0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 6 )); then
+    echo "ERROR with translator \"${S}\" on bad read in e-tautological clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo -e "p cnf 0 1\n0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 0 )); then
+    echo "ERROR with translator \"${S}\" on legal empty clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 0 1\n0" | $S "-cin" -nil -nil n 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 9 )); then
+    echo "ERROR with translator \"${S}\" on illegal empty clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo -e "p cnf 1 1\na 1 0\n1 0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 0 )); then
+    echo "ERROR with translator \"${S}\" on legal pseudoempty clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+set +e
+  echo -e "p cnf 1 1\na 1 0\n1 0" | $S "-cin" -nil -nil s 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 24 )); then
+    echo "ERROR with translator \"${S}\" on illegal pseudoempty clause: wrong return-code ${returncode}."
+    exit 1
+  fi
+
 
   file="${testdir}/Maxima_2903.dqdimacs"
 set +e
