Managing now also the original clause-indices.

diff --git a/Satisfiability/Quantification/DQCNF/app_tests/RunTests b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
--- a/Satisfiability/Quantification/DQCNF/app_tests/RunTests
+++ b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
@@ -3,7 +3,7 @@ set -o errexit
 set -o nounset
 
 program="RunTests"
-version="0.1.1"
+version="0.1.2"
 
 testdir="app_tests"
 
@@ -147,7 +147,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 1 0\na 1 0\na 0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 1 0\na 1 0\na 0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -192,7 +192,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 1 0\na 0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 1 0\na 0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -212,7 +212,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 1 0\ne 1 0\ne 0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 1 0\ne 1 0\ne 0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -257,7 +257,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 1 0\ne 0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 1 0\ne 0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -302,7 +302,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 2 0\na 1 0\nd 2 0" | $S "-cin" -nil -nil vs 2> /dev/null
+  echo -e "p cnf 2 0\na 1 0\nd 2 0" | $S "-cin" -nil -nil vs
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -338,7 +338,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 2 0\na 1 0\nd 2 1 0" | $S "-cin" -nil -nil vs 2> /dev/null
+  echo -e "p cnf 2 0\na 1 0\nd 2 1 0" | $S "-cin" -nil -nil vs
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -443,7 +443,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 0 1\n0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 0 1\n0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -460,7 +460,7 @@ set -e
   fi
 
 set +e
-  echo -e "p cnf 1 1\na 1 0\n1 0" | $S "-cin" -nil -nil g 2> /dev/null
+  echo -e "p cnf 1 1\na 1 0\n1 0" | $S "-cin" -nil -nil g
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -485,7 +485,7 @@ set -e
     exit 1
   fi
 set +e
-  echo -e "p cnf 1 1\n1 -1 0" | $S "-cin" -nil -nil vs 2> /dev/null
+  echo -e "p cnf 1 1\n1 -1 0" | $S "-cin" -nil -nil vs
   returncode=$?
 set -e
   if(( returncode != 0 )); then
@@ -501,13 +501,48 @@ set -e
     exit 1
   fi
 set +e
-  echo -e "p cnf 1 7\n1 -1 0 1 -1 0 1 -1 0 1 0 1 0 -1 0 -1 0" | $S "-cin" -nil -nil s 2> /dev/null
+  echo -e "p cnf 1 7\n1 -1 0 1 -1 0 1 -1 0 1 0 1 0 -1 0 -1 0" | $S "-cin" -nil -nil s
   returncode=$?
 set -e
   if(( returncode != 0 )); then
     echo "ERROR with translator \"${S}\" on legal example (tautological and repeated clauses): wrong return-code ${returncode}."
     exit 1
   fi
+
+set +e
+  echo -e "p cnf 1 7\n1 1 -1 -1 0 -1 1 1 -1 0 1 1 -1 0 1 1 0 1 1 0 -1 -1 0 -1 0" | $S "-cin" -nil ${tempfile} s 2
+  returncode=$?
+set -e
+  if(( returncode != 0 )); then
+    echo "ERROR with translator \"${S}\" on legal example (tautological and repeated clauses): wrong return-code ${returncode}."
+    exit 1
+  fi
+  result=$(cat ${tempfile} | awk '/c number_tautological_clauses/{print $3}')
+  if (( result != 3 )); then
+    echo -e "Wrong tautological-clauses count ${result} != 3 with translator \"${S}\"."
+    exit 1
+  fi
+  result=$(cat ${tempfile} | awk '/c number_repeated_clauses/{print $3}')
+  if (( result != 2 )); then
+    echo -e "Wrong repeated-clauses count ${result} != 2 with translator \"${S}\"."
+    exit 1
+  fi
+  result=$(cat ${tempfile} | awk '/c number_repeated_literals/{print $3}')
+  if (( result != 3 )); then
+    echo -e "Wrong repeated-literals count ${result} != 3 with translator \"${S}\"."
+    exit 1
+  fi
+  result=$(cat ${tempfile} | awk '/c  1: E: -1/{print $6}')
+  if (( result != 6 )); then
+    echo -e "Wrong original-clause-index ${result} != 6 with translator \"${S}\"."
+    exit 1
+  fi
+  result=$(cat ${tempfile} | awk '/c  2: E: 1/{print $6}')
+  if (( result != 4 )); then
+    echo -e "Wrong original-clause-index ${result} != 4 with translator \"${S}\"."
+    exit 1
+  fi
+  rm ${tempfile}
 
 
   file="${testdir}/Maxima_2903.dqdimacs"
@@ -516,12 +551,12 @@ set +e
   returncode=$?
 set -e
   if (( returncode != 0 )); then
-    echo "ERROR with translator \"${S}\" on ${file}."
+    echo "ERROR with translator \"${S}\" on ${file}: wrong return-code ${returncode}."
     exit 1
   fi
   result=$(${countsolver1} ${tempfile} | awk '/number_of_solutions/{print $3}')
   if (( result != 2903 )); then
-    echo -e "Wrong count with translator \"${S}\" on ${file}."
+    echo -e "Wrong count ${result} != 2903 with translator \"${S}\" on ${file}."
     exit 2
   fi
   rm ${tempfile}
