Outputting error-line-numbers for header-errors.

diff --git a/Satisfiability/Quantification/DQCNF/app_tests/RunTests b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
--- a/Satisfiability/Quantification/DQCNF/app_tests/RunTests
+++ b/Satisfiability/Quantification/DQCNF/app_tests/RunTests
@@ -38,6 +38,87 @@ set -e
     exit 1
   fi
 
+set +e
+  echo " " | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 26 )); then
+    echo "ERROR with translator \"${S}\" on bad comment-line: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (no space): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line: wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p " | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (no \"cnf\"): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p cnf" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (no n): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p cnf x" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (bad n): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p cnf 3000000000" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 4 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (large n): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p cnf 0" | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 27 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (bad c): wrong return-code ${returncode}."
+    exit 1
+  fi
+
+set +e
+  echo "p cnf 0 0 " | $S "-cin" -nil -nil g 2> /dev/null
+  returncode=$?
+set -e
+  if(( returncode != 3 )); then
+    echo "ERROR with translator \"${S}\" on bad p-line (trailing): wrong return-code ${returncode}."
+    exit 1
+  fi
+
   file="${testdir}/Maxima_2903.dqdimacs"
 set +e
   $S ${file} ${tempfile} ${tempfile} vs 1
