oklib now supports also pushing and pulling to remote repositories.

diff --git a/Buildsystem/MasterScript/oklib b/Buildsystem/MasterScript/oklib
--- a/Buildsystem/MasterScript/oklib
+++ b/Buildsystem/MasterScript/oklib
@@ -11,7 +11,7 @@ if [[ $# == 0 ]]; then
   exit 0
 fi
 
-version=0.1.0.7
+version=0.1.0.8
 
 if [[ $1 == "--version" ]]; then
   echo "oklib version ${version}"
@@ -74,6 +74,104 @@ if [[ $1 == "--R" ]]; then
   ${command}
   exit
 fi
+
+if [[ $1 == "--push-developer" ]]; then
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the username of the developer on the server is needed as parameter!\n"
+    exit 1
+  fi
+  developer=$1
+  shift
+  if [[ $# == 0 ]]; then
+    git_arguments=""
+  else
+    git_arguments="$*"
+  fi
+  command="make --makefile=${buildsystem_dir}/SourceControl/Makefile OKplatform=${top_dir} developer_okl=${developer} git_arguments_okl=${git_arguments} push_developers"
+  echo ${command}
+  ${command}
+  exit
+fi
+if [[ $1 == "--pull-developer" ]]; then
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the username of the developer on the server is needed as parameter!\n"
+    exit 1
+  fi
+  developer=$1
+  shift
+  if [[ $# == 0 ]]; then
+    git_arguments=""
+  else
+    git_arguments="$*"
+  fi
+  command="make --makefile=${buildsystem_dir}/SourceControl/Makefile OKplatform=${top_dir} developer_okl=${developer} git_arguments_okl=${git_arguments} pull_developers"
+  echo ${command}
+  ${command}
+  exit
+fi
+if [[ $1 == "--pull-public" ]]; then
+  shift
+  if [[ $# == 0 ]]; then
+    git_arguments=""
+  else
+    git_arguments="$*"
+  fi
+  command="make --makefile=${buildsystem_dir}/SourceControl/Makefile OKplatform=${top_dir} git_arguments_okl=${git_arguments} pull_public"
+  echo ${command}
+  ${command}
+  exit
+fi
+if [[ $1 == "--push-ssh" ]]; then
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the username on the remote machine is needed as parameter!\n"
+    exit 1
+  fi
+  username=$1
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the remote OKplatform-directory is needed as parameter!\n"
+    exit 1
+  fi
+  repository=$1
+  shift
+  if [[ $# == 0 ]]; then
+    git_arguments=""
+  else
+    git_arguments="$*"
+  fi
+  command="make --makefile=${buildsystem_dir}/SourceControl/Makefile OKplatform=${top_dir} username_okl=${username} remote_repository_okl=${repository} git_arguments_okl=${git_arguments} push_ssh"
+  echo ${command}
+  ${command}
+  exit
+fi
+if [[ $1 == "--pull-ssh" ]]; then
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the username on the remote machine is needed as parameter!\n"
+    exit 1
+  fi
+  username=$1
+  shift
+  if [[ $# == 0 ]]; then
+    echo -e "ERROR[oklib]: the remote OKplatform-directory is needed as parameter!\n"
+    exit 1
+  fi
+  repository=$1
+  shift
+  if [[ $# == 0 ]]; then
+    git_arguments=""
+  else
+    git_arguments="$*"
+  fi
+  command="make --makefile=${buildsystem_dir}/SourceControl/Makefile OKplatform=${top_dir} username_okl=${username} remote_repository_okl=${repository} git_arguments_okl=${git_arguments} pull_ssh"
+  echo ${command}
+  ${command}
+  exit
+fi
+
 
 
 oklib_building_log=${anchor_dir}/log/OKlibBuilding
