Correction: output must be put into quotation marks.
Also removed superfluous semicolons.

diff --git a/Satisfiability/Solvers/OKsolver/SAT2002/app_tests/all_combinations b/Satisfiability/Solvers/OKsolver/SAT2002/app_tests/all_combinations
--- a/Satisfiability/Solvers/OKsolver/SAT2002/app_tests/all_combinations
+++ b/Satisfiability/Solvers/OKsolver/SAT2002/app_tests/all_combinations
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Oliver Kullmann, 19.8.2007 (Swansea)
-# Copyright 2007, 2008 Oliver Kullmann
+# Copyright 2007, 2008, 2009 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
@@ -29,21 +29,23 @@ echo "EXECUTION OF SOLVERS:"
 match_tool=${bin_dir}/MatchFiles-O3-DNDEBUG
 
 for S in ${list_solvers}; do
-  echo;
+  echo
   for P in ${list_test_cases}; do
-    echo ${S} ${P};
-    output=$(${S} ${P});
+    echo ${S} ${P}
+    output="$(${S} ${P})"
     case ${S} in
     *_osa*) template=$(dirname ${P})/dimacs_output/osa/$(basename ${P} .cnf)
         ;;
     *) template=$(dirname ${P})/dimacs_output/$(basename ${P} .cnf)
         ;;
     esac
-    echo ${output} | ${match_tool} ${template};
-    result=$?;
+    echo "${output}" | ${match_tool} ${template}
+    result=$?
     if [[ ${result} != 0 ]]; then
-      echo -e "ERROR: OUTPUT of solver is\n${output}\n, while TEMPLATE is";
-      cat ${template}; echo; exit 1;
+      echo -e "ERROR: OUTPUT of solver is\n${output}\n, while TEMPLATE is"
+      cat ${template}
+      echo
+      exit 1
     fi;
   done;
 done
