Tool AddLicence1 ready now for inserting licences in C/C++-like files.
Made also amendments to the short licence text.

diff --git a/System/LegalIssues/AddLicence1 b/System/LegalIssues/AddLicence1
--- a/System/LegalIssues/AddLicence1
+++ b/System/LegalIssues/AddLicence1
@@ -1,6 +1,42 @@
 #!/bin/bash
 # Oliver Kullmann, 25.8.2007 (Swansea)
 
-head --lines=1 $1 | cat - Header.h > $$; tail --lines=+2 $1 | cat $$ -
+# One input parameter is expected, a filename.
+# If the first line matches the regular expression (BRE)
+# ^// .+ \(200.\) (.+)$
+# then Header.h is inserted right after the first line,
+# where XXXX is replaced either by "\1-2007" in case
+# \1 is not 2007, or otherwise just by "2007".
 
-rm $$
+set -o errexit -o nounset # -o xtrace
+shopt -s extglob
+
+licence_text_file=${OKPLATFORM}/OKsystem/Transitional/System/LegalIssues/Header.h
+
+if [ $# != 1 ]; then
+  echo "ERROR[AddLicence1]: Exactly one input parameter is expected, the name of the file where the licence is to be inserted!"
+  exit 1
+fi
+
+first_line=$(head --lines=1 $1)
+
+if [[ "${first_line}" =~ "^// .*(200.).*\(.+\) *$" ]]; then
+  year=${BASH_REMATCH[1]}
+  if [ "${year}" == "2007" ]; then
+    replacement="2007"
+  else
+    replacement="${year} - 2007"
+  fi
+
+  echo ${first_line} > $$
+  sed -e "s;XXXX;${replacement};" ${licence_text_file} >> $$
+  tail --lines=+2 $1 >> $$
+
+  mv $$ $1
+
+else
+
+  echo $1
+
+fi
+
