Added missing creation dates for AES scripts.
Also:
 - added version numbers and error checking for some scripts.
 - amended existing todo on improving scripts.

diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/all_minimum_cnf b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/all_minimum_cnf
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/all_minimum_cnf
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/all_minimum_cnf
@@ -1,23 +1,25 @@
 #! /bin/bash
+# Matthew Gwynne, 5.1.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
 
-set -o errexit
-set -o nounset
-
-script_name="all_minimum_cnfs"
-version="0.2.1"
-
 # Script which given the path to a full Dimacs CNF file "strict_file"
 # computes all minimum CNF representations of this file
 # and then generates files with the names ${strict_file}.trans_$i containing 
 # the i-th minimum size CNF representation for all i.
 
+set -o errexit
+set -o nounset
+
+script_name="all_minimum_cnf"
+version="0.2.2"
+
+err="ERROR[${script_name}]"
 if [[ $# > 2 || $# < 1 ]]; then
-  echo "Error[all_minimum_cnf]: Takes two arguments, the path to the full Dimacs CNF file of which the minimum CNF representations should be generated and optionally a lower bound on the size of the minimum CNF representations."
+  echo "${err}: Takes two arguments, the path to the full Dimacs CNF file of which the minimum CNF representations should be generated and optionally a lower bound on the size of the minimum CNF representations."
   exit 1;
 fi
 
diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/find_r1bases b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/find_r1bases
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/find_r1bases
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/find_r1bases
@@ -1,16 +1,10 @@
 #!/bin/bash
+# Matthew Gwynne, 27.1.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
-
-set -o errexit
-set -o nounset
-
-script_name="find_rbases"
-err="ERROR[${script_name}]:"
-version="0.0.4"
 
 #
 # Given a full CNF in a Dimacs file, computes random r_1 bases for
@@ -37,6 +31,13 @@ version="0.0.4"
 # where ${gen_seed} is the current seed, and ${base_seed} is the current
 # seed being passed to the RandomShuffleDimacs call leading into RUcpBase (1-t).
 #
+
+set -o errexit
+set -o nounset
+
+script_name="find_r1bases"
+err="ERROR[${script_name}]:"
+version="0.2.0"
 
 if [[ $# -lt 1 || $# -gt 3 ]]; then
   echo -n "${err} Takes precisely one argument, the name of the file full "
diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/generate_aes_experiment b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/generate_aes_experiment
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/generate_aes_experiment
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/generate_aes_experiment
@@ -1,17 +1,10 @@
 #!/bin/bash
-# BUG: missing file-creation information
+# Matthew Gwynne, 3.2.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
-
-set -o errexit
-set -o nounset
-
-script_name="generate_aes_experiment"
-err="ERROR[${script_name}]:"
-version="0.0.4"
 
 #
 # Generates AES CNF translations and plaintext-ciphertext variable assignments 
@@ -75,6 +68,13 @@ version="0.0.4"
 #   and ss_random_pc_pair yielding files with names in the format
 #   ss_r${r}_* and ssaes_pcpair_r${r}_*_s${k}.cnf.
 # 
+
+set -o errexit
+set -o nounset
+
+script_name="generate_aes_experiment"
+err="ERROR[${script_name}]:"
+version="0.1.2"
 
 if [[ ! $# -eq 8 ]]; then
   echo -n "${err} Takes exactly eight arguments, the number of rounds, number ",
diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_aes_experiment b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_aes_experiment
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_aes_experiment
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_aes_experiment
@@ -1,18 +1,11 @@
 #!/bin/bash
+# Matthew Gwynne, 6.2.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
 
-# set -o errexit # Can't use as SAT solvers return non-zero.
-set -o nounset
-
-script_name="run_aes_experiment"
-err="ERROR[${script_name}]:"
-version="0.0.2"
-
-# BUG: misleading version number
 
 #
 # Goes through all combinations of AES translations and plaintext-ciphertext
@@ -66,6 +59,13 @@ version="0.0.2"
 #   the experiment directory. If there is, this file will be overwritten
 #   and then deleted.
 #
+
+# set -o errexit # Can't use as SAT solvers return non-zero.
+set -o nounset
+
+script_name="run_aes_experiment"
+err="ERROR[${script_name}]:"
+version="0.1.0"
 
 if [[ ! $# -eq 8 ]]; then
   echo -n "${err} Takes exactly eight arguments, the number of rounds, number ",
diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_all_solvers_2by2 b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_all_solvers_2by2
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_all_solvers_2by2
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/run_all_solvers_2by2
@@ -1,16 +1,10 @@
 #!/bin/bash
+# Matthew Gwynne, 4.2.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
-
-#set -o errexit # Interferes with operation of subshell, SAT solvers return non-zero
-set -o nounset
-
-script_name="run_all_solvers_2by2"
-err="ERROR[${script_name}]:"
-version="0.0.6"
 
 #
 # Takes the path to a Dimacs CNF file and runs all solvers in the OKlibrary,
@@ -25,6 +19,13 @@ version="0.0.6"
 #
 # The script exits when all solvers have finished.
 #
+
+#set -o errexit # Interferes with operation of subshell, SAT solvers return non-zero
+set -o nounset
+
+script_name="run_all_solvers_2by2"
+err="ERROR[${script_name}]:"
+version="0.1.0"
 
 if [[ ! $# -eq 1 ]]; then
   echo -n "${err} Takes precisely one argument, the name of the Dimacs "
diff --git a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/validate_aes_assignment b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/validate_aes_assignment
--- a/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/validate_aes_assignment
+++ b/Experimentation/Investigations/Cryptography/AdvancedEncryptionStandard/validate_aes_assignment
@@ -1,26 +1,20 @@
 #!/bin/bash
+# Matthew Gwynne, 22.1.2011 (Swansea)
 # Copyright 2011 Oliver Kullmann
 # This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
 # it and/or modify it under the terms of the GNU General Public License as published by
 # the Free Software Foundation and included in this library; either version 3 of the 
 # License, or any later version.
 
-set -o errexit
-set -o nounset
-
-script_name="validate_aes_assignment"
-err="ERROR[${script_name}]:"
-version="0.1.4"
-
 #
 # Script to check that the satisfying assignment returned from a SAT solver for
-# the AES problem specified by the parameters given as arguments to this script, 
-# is a valid assignment. 
+# the AES problem, specified by the parameters given as arguments to this script, 
+# is a valid assignment.
 # 
 # In other words, the plaintext represented by the first num_columns * num_rows 
-# * exp bits, along with the key represented by the next set of bits, of the 
+# * exp bits, along with the key represented by the next set of bits of the 
 # same length, encrypts to the ciphertext given in the next set of bits 
-# (2*num_columns*num_rows*exp+1 - num_columns*num_rows*exp).
+# (2*num_columns*num_rows*exp+1 .. num_columns*num_rows*exp).
 #
 # See ss_validate in 
 # OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/Translations.mac .
@@ -44,6 +38,13 @@ version="0.1.4"
 #   Returns 0 if the partial assignment represents a valid AES/small scale
 #   encryption, or non-zero otherwise.
 # 
+
+set -o errexit
+set -o nounset
+
+script_name="validate_aes_assignment"
+err="ERROR[${script_name}]:"
+version="0.1.5"
 
 if [[ $# -ne 5 ]]; then
   echo -n "${err} Takes precisely 5 arguments, the number of rounds, "
